### ISSUE TITLE
K2+SE integration

### ISSUE THREAD

**Issue by Qatavin** [modded-factorio/bobsmods#153]
Since it's a popular combination that people have been requesting we fix, I've been looking at what to do about K2+SE integration. Fixing the crashes that occur is easy enough, but I figure that if we're going to do this, we should do it right. Here are the crashes, redundancies, and other issues I've identified that I believe we should fix in the next version. It would be helpful if someone could double check to make sure I haven't missed anything and provide additional opinions.

### Logistics:
- [x] (K2 crash) Change hidden long handed inserter entity next_upgrade to nil (#154)
- [ ] Hide K2 superior inserters
- [x] (K2 crash) Change pump 1 fast_replaceable_group back to "pipe" (#154)
- [ ] Hide K2 advanced+superior belts
- [ ] Adjust K2 loader speeds to work with Bob's purple and green belts, and move them to Bob's logistics techs (note: make sure to account for settings that adjust belt speed)
- [ ] Hide redundant K2 steel pipe
- [ ] Hide K2 redundant steel pump
- [ ] Hide K2 large storage tank
- [ ] Adjust K2 huge storage tank recipe
- [ ] Restore standard storage tank 1 recipe

### Mining:
- [ ] Hide K2 redundant mining drill 2+3, replace K2drill2 on SE big mining drill with Bob mining drill 2
- [ ] Add rare metals to Bob mining drills 3?

### Assembling:
- [x] (K2 crash) Add logic to account for K2 changing electric furnace 2 to an assembling machine instead of a furnace (#151)

**Comment by Brilliand** [comment]
There's _so much_ overlap between K2 and Bob's Logistics that it doesn't really seem worth making those compatible to me?

Just provide compatibility for the things that make sense together.

**Comment by Qatavin** [comment]
I do agree with you, which is why I didn't account for K2 before, and yet we've had multiple people bringing up these issues, so...

**Comment by Qatavin** [comment]
I've taken care of all of these on my end.
